name: Create a local sorted copy of the blog's query index

on:
  schedule:
    # Every hour at 03
    - cron: '3 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-blog-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run sorting scripts
        run: node sorted-index/sort-query-index.js
        
      - name: Commit and push changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (sort query index)"
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -am "Update sorted query index - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push
